version: '3.4'

services:
  medcentreloggingapi:
    image: swanseauniversitymedical/medcentre-dev
    container_name: medcentre
    env_file: ../medcentre.config
    ports:
      - "3002:80"
      
  medCentreLoggingDb:
    image: postgres:alpine
    env_file: ../medcentre.config
    volumes:
      - type: volume
        source: medCentreLoggingDbVol
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure

  vault:
    image: vault:0.9.3
    env_file: ../medcentre.config
    ports:
      - "8200:8200"
    restart: on-failure
    cap_add: [IPC_LOCK]

  vaultUI:
    image: djenriquez/vault-ui:latest
    environment:
      - VAULT_URL_DEFAULT=vault
      - VAULT_AUTH_DEFAULT=TOKEN
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - vault
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: medcentreES
    env_file: ../medcentre.config
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: medcentreESVol
        target: /usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    container_name: medcentreKibana
    environment:
      - elasticsearch.url= http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch

volumes:
  medCentreLoggingDbVol:
  medcentreESVol:
